import {
  Code,
  LayoutDashboard,
  ShoppingCart,
  Smartphone,
  Server,
  CreditCard,
  Bot,
  Rocket,
  Palette,
  LifeBuoy,
} from "lucide-react";


// Projects Data
export const projects = [
{
  title: "Space Sculpt",
  category: "Website | Development",
  image: "/project-images/spacesculpt.png",
  link: "https://space-sculpt.vercel.app/",
  year: 2024,
},
{
  title: "DBQ Pro",
  category: "Website | Development",
  image: "/project-images/dbq-pro.png",
  link: "https://dbq-pro-puce.vercel.app/",
  year: 2023,
},
{
  title: "LED Display UAE",
  category: "Website | Development",
  image: "/project-images/uae-led.png",
  link: "https://www.leddisplayuae.com/",
  year: 2022,
},
{
  title: "Alghwasa",
  category: "Website | Development",
  image: "/project-images/alghwasa.png",
  link: "https://www.alghwasa.com/",
  year: 2024,
},
{
  title: "Honesty Engineering Works",
  category: "Website | Development",
  image: "/project-images/honesty.png",
  link: "https://www.honestyengineering.in/",
  year: 2021,
},
{
  title: "Pop and Palm",
  category: "Website | Development",
  image: "/project-images/pop-and-palm.png",
  link: "https://www.popandpalmevents.com/",
  year: 2023,
},
{
  title: "Pixel World",
  category: "Website | Development",
  image: "/project-images/pixel-world.png",
  link: "https://www.pixelworld.ae/",
  year: 2024,
},
{
  title: "EOM",
  category: "Website | Development",
  image: "/project-images/eom.png",
  link: "https://www.entrepreneursofmadras.com/",
  year: 2023,
},
{
  title: "SunnySide Up",
  category: "Website | Development",
  image: "/project-images/sunny-side.png",
  link: "https://sunnysidecafe.vercel.app/",
  year: 2024,
},
{
  title: "Kind Rice",
  category: "Website | Development",
  image: "/project-images/kind-rice.png",
  link: "https://www.kindrice.co/",
  year: 2022,
},
{
  title: "Zarak Media",
  category: "Website | Development",
  image: "/project-images/zarak.png",
  link: "https://codeerr-sid.github.io/Zarak_Media/",
  year: 2021,
},
{
  title: "Braai Shack",
  category: "Website | Development",
  image: "/project-images/braai.png",
  link: "https://braaishack.vercel.app/",
  year: 2024,
},
{
  title: "Sri Varsha",
  category: "Website | Development",
  image: "/project-images/srivarsha.png",
  link: "https://sri-varsha.vercel.app/index.html",
  year: 2020,
},
{
  title: "Prepco Healthcare",
  category: "Website | Development",
  image: "/project-images/prepco.png",
  link: "https://prepcohealthcare.com/",
  year: 2023,
},

];

// Expertise Data
export const expertiseData = [
  {
    title: "Web & App Development",
    description: "Building high-performance, scalable digital products using cutting-edge technologies.",
    icon: Code,
    color: "from-blue-500/20 to-primary/20",
    points: [
      "Fast, responsive & device-friendly builds",
      "Scalable architecture for future growth",
      "Modern tech stack & best coding practices",
      "Customized to your brand & goals",
    ],
  },
  {
    title: "Custom Web Applications & Dashboards",
    description: "Tailor-made applications and dashboards designed to automate workflows and visualize business data.",
    icon: LayoutDashboard,
    color: "from-purple-500/20 to-pink-500/20",
    points: [
      "Custom workflows & automation",
      "Real-time data visualization",
      "Secure authentication & access control",
      "Built to align with internal operations",
    ],
  },
  {
    title: "E-commerce & Marketplace Solutions",
    description: "End-to-end marketplace platforms with secure transactions, logistics, and custom product logic.",
    icon: ShoppingCart,
    color: "from-amber-500/20 to-orange-500/20",
    points: [
      "Payment integration (UPI, Stripe, Razorpay, PayPal, etc.)",
      "Shipping integration with live tracking",
      "Inventory management & stock control",
      "Analytics for sales & performance",
      "Custom logic for unique/special products",
    ],
  },
  {
    title: "Mobile App Development",
    description: "Native and cross-platform mobile apps built for performance, reliability, and user engagement.",
    icon: Smartphone,
    color: "from-green-500/20 to-emerald-500/20",
    points: [
      "iOS & Android app development",
      "Native & cross-platform builds",
      "Smooth UI/UX experiences",
      "API connectivity & cloud sync",
    ],
  },
  {
    title: "Backend & API Development",
    description: "Secure, scalable server architecture and APIs engineered for seamless integration and data flow.",
    icon: Server,
    color: "from-gray-500/20 to-blue-500/20",
    points: [
      "REST & GraphQL APIs",
      "Authentication & authorization systems",
      "High-performance data handling",
      "Optimized cloud-based server setups",
    ],
  },
  {
    title: "Payment & Financial Integrations",
    description: "Payment gateways, subscription billing, invoicing, and financial systems your users can trust.",
    icon: CreditCard,
    color: "from-indigo-500/20 to-primary/20",
    points: [
      "Payment gateway setup (Stripe, Razorpay, PayPal, etc.)",
      "Subscription billing & recurring payments",
      "Automated invoicing & receipts",
      "Fraud protection & compliance setup",
    ],
  },
  {
    title: "AI & Automation Solutions",
    description: "Smart automation, chatbots, machine learning, and AI integrations to accelerate productivity.",
    icon: Bot,
    color: "from-teal-500/20 to-cyan-500/20",
    points: [
      "Conversational chatbots",
      "Process automation & workflow bots",
      "Predictive analytics & ML models",
      "AI-powered customer & business ops",
    ],
  },
  {
    title: "SEO & Performance Optimization",
    description: "Boost visibility, speed, rankings, and conversions with technical SEO and performance upgrades.",
    icon: Rocket,
    color: "from-yellow-500/20 to-lime-500/20",
    points: [
      "Technical SEO & site structure",
      "Web vitals & speed optimization",
      "Improved ranking & discoverability",
      "Conversion-focused UX improvements",
    ],
  },
  {
    title: "UI/UX Design",
    description: "User-centered design that blends aesthetics with seamless, intuitive digital experiences.",
    icon: Palette,
    color: "from-pink-500/20 to-rose-500/20",
    points: [
      "Wireframes & prototypes",
      "Visual identity & branding",
      "User journey & navigation flow",
      "Design systems & consistency",
    ],
  },
  {
    title: "Maintenance & Support",
    description: "Reliable, ongoing maintenance, updates, bug fixes, and security monitoring for peace of mind.",
    icon: LifeBuoy,
    color: "from-slate-500/20 to-slate-700/20",
    points: [
      "Security patches & monitoring",
      "Bug fixes & error resolution",
      "Feature updates & enhancements",
      "Backups, recovery & uptime care",
    ],
  },
];

// Packages Data
export const packages = [
  {
    name: "Basic",
    price: "₹4999",
    description: "Perfect for startups and simple digital presence.",
    features: [
      "Single Page Website",
      "Responsive Design",
      "Basic SEO Setup",
      "Contact Form Integration",
      "2 Rounds of Revisions",
    ],
    buttonText: "Start Basic Plan",
    popular: false,
  },
  {
    name: "Standard",
    price: "₹14999",
    description: "The complete solution for growing businesses.",
    features: [
      "Up to 5 Pages",
      "Custom UI/UX Design",
      "CMS Integration",
      "Speed Optimization",
      "Advanced SEO",
      "5 Rounds of Revisions",
    ],
    buttonText: "Choose Standard",
    popular: true,
  },
  {
    name: "Premium",
    price: "₹19999",
    description: "Enterprise-grade digital experiences.",
    features: [
      "Fully Custom Web App",
      "E-commerce Functionality",
      "Premium Animations",
      "Database Integration",
      "Priority 24/7 Support",
      "Unlimited Revisions",
    ],
    buttonText: "Get Premium",
    popular: false,
  },
];

